spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/mentora
spring.datasource.username=mentora_app
spring.datasource.password=${MENTORA_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate